config/routes.rb
BarleyBreak::Application.routes.draw do
  get "game/show"
  root "welcome#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def show
  	@array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, nil].shuffle
  end  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/game/show.html.erb
<h1>ПЯТНАШКИ</h1>
<table border="2">
<% for row in 0..3 %>
     <tr>  
     <% for col in 0..3 %>   
        <td ALIGN=center WIDTH=50 HEIGHT=50><%= link_to @array[row*4+col], game_show_path %></td>
    <% end %>
    </tr>
<% end %> 
</table>
<% if @array[row + 1 , col] == 0
  	@array[row + 1, col] = @array[row, col] and @array[row, col]=0
  elsif @array[row - 1 , col] == 0	
  	@array[row - 1, col] = @array[row, col] and @array[row, col]=0
  elsif @array[row , col - 1] == 0	
  	@array[row, col - 1] = @array[row, col] and @array[row, col]=0
  elsif @array[row , col + 1] == 0	
  	@array[row, col + 1] = @array[row, col] and @array[row, col]=0
  end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BarleyBreak</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Скучно? Поиграем?</h1>
<p>
<%= link_to "играть", game_show_path %>
</p>